name: "Drewpol:
version: "1.0"
description: "Addon zapisujący dane z formularza do pliku i pokazujący wpisy"
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:form-select
host_network: true
init: false
